window.esdocSearchIndex = [
  [
    "truffle-debugger/lib/session/reducers.js~active",
    "variable/index.html#static-variable-ACTIVE",
    "<span>ACTIVE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~add_context",
    "variable/index.html#static-variable-ADD_CONTEXT",
    "<span>ADD_CONTEXT</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~add_instance",
    "variable/index.html#static-variable-ADD_INSTANCE",
    "<span>ADD_INSTANCE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/solidity/actions/index.js~add_source",
    "variable/index.html#static-variable-ADD_SOURCE",
    "<span>ADD_SOURCE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/solidity/actions/index.js~add_sourcemap",
    "variable/index.html#static-variable-ADD_SOURCEMAP",
    "<span>ADD_SOURCEMAP</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~advance",
    "variable/index.html#static-variable-ADVANCE",
    "<span>ADVANCE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/data/actions/index.js~assign",
    "variable/index.html#static-variable-ASSIGN",
    "<span>ASSIGN</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~begin_step",
    "variable/index.html#static-variable-BEGIN_STEP",
    "<span>BEGIN_STEP</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~call",
    "variable/index.html#static-variable-CALL",
    "<span>CALL</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~continue_until",
    "variable/index.html#static-variable-CONTINUE_UNTIL",
    "<span>CONTINUE_UNTIL</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~create",
    "variable/index.html#static-variable-CREATE",
    "<span>CREATE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/data/actions/index.js~declare",
    "variable/index.html#static-variable-DECLARE",
    "<span>DECLARE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/ast/actions/index.js~done_visiting",
    "variable/index.html#static-variable-DONE_VISITING",
    "<span>DONE_VISITING</span> <span class=\"search-result-import-path\">truffle-debugger/lib/ast/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/debugger.js~debugger",
    "class/lib/debugger.js~Debugger.html",
    "<span>Debugger</span> <span class=\"search-result-import-path\">truffle-debugger/lib/debugger.js</span>",
    "class"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~end_of_trace",
    "variable/index.html#static-variable-END_OF_TRACE",
    "<span>END_OF_TRACE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/session/actions/index.js~error",
    "variable/index.html#static-variable-ERROR",
    "<span>ERROR</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/session/reducers.js~error",
    "variable/index.html#static-variable-ERROR",
    "<span>ERROR</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~error_web3",
    "variable/index.html#static-variable-ERROR_WEB3",
    "<span>ERROR_WEB3</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~fetch_binary",
    "variable/index.html#static-variable-FETCH_BINARY",
    "<span>FETCH_BINARY</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/session/actions/index.js~finish",
    "variable/index.html#static-variable-FINISH",
    "<span>FINISH</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/session/reducers.js~finished",
    "variable/index.html#static-variable-FINISHED",
    "<span>FINISHED</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~init_web3",
    "variable/index.html#static-variable-INIT_WEB3",
    "<span>INIT_WEB3</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~inspect",
    "variable/index.html#static-variable-INSPECT",
    "<span>INSPECT</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~interrupt",
    "variable/index.html#static-variable-INTERRUPT",
    "<span>INTERRUPT</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/solidity/actions/index.js~jump",
    "variable/index.html#static-variable-JUMP",
    "<span>JUMP</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~max_word",
    "variable/index.html#static-variable-MAX_WORD",
    "<span>MAX_WORD</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~next",
    "variable/index.html#static-variable-NEXT",
    "<span>NEXT</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/session/actions/index.js~ready",
    "variable/index.html#static-variable-READY",
    "<span>READY</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~receive_addresses",
    "variable/index.html#static-variable-RECEIVE_ADDRESSES",
    "<span>RECEIVE_ADDRESSES</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~receive_binary",
    "variable/index.html#static-variable-RECEIVE_BINARY",
    "<span>RECEIVE_BINARY</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~receive_call",
    "variable/index.html#static-variable-RECEIVE_CALL",
    "<span>RECEIVE_CALL</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~receive_trace",
    "variable/index.html#static-variable-RECEIVE_TRACE",
    "<span>RECEIVE_TRACE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/session/actions/index.js~record_contracts",
    "variable/index.html#static-variable-RECORD_CONTRACTS",
    "<span>RECORD_CONTRACTS</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~return",
    "variable/index.html#static-variable-RETURN",
    "<span>RETURN</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~save_steps",
    "variable/index.html#static-variable-SAVE_STEPS",
    "<span>SAVE_STEPS</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/data/actions/index.js~scope",
    "variable/index.html#static-variable-SCOPE",
    "<span>SCOPE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/session/actions/index.js~start",
    "variable/index.html#static-variable-START",
    "<span>START</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~step_into",
    "variable/index.html#static-variable-STEP_INTO",
    "<span>STEP_INTO</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~step_next",
    "variable/index.html#static-variable-STEP_NEXT",
    "<span>STEP_NEXT</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~step_out",
    "variable/index.html#static-variable-STEP_OUT",
    "<span>STEP_OUT</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~step_over",
    "variable/index.html#static-variable-STEP_OVER",
    "<span>STEP_OVER</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/session/index.js~session",
    "class/lib/session/index.js~Session.html",
    "<span>Session</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/index.js</span>",
    "class"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~tick",
    "variable/index.html#static-variable-TICK",
    "<span>TICK</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~tock",
    "variable/index.html#static-variable-TOCK",
    "<span>TOCK</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/ast/actions/index.js~visit",
    "variable/index.html#static-variable-VISIT",
    "<span>VISIT</span> <span class=\"search-result-import-path\">truffle-debugger/lib/ast/actions/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/session/reducers.js~waiting",
    "variable/index.html#static-variable-WAITING",
    "<span>WAITING</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~word_size",
    "variable/index.html#static-variable-WORD_SIZE",
    "<span>WORD_SIZE</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/web3/adapter.js~web3adapter",
    "class/lib/web3/adapter.js~Web3Adapter.html",
    "<span>Web3Adapter</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/adapter.js</span>",
    "class"
  ],
  [
    "truffle-debugger/lib/store/common.js~abbreviatevalues",
    "function/index.html#static-function-abbreviateValues",
    "<span>abbreviateValues</span> <span class=\"search-result-import-path\">truffle-debugger/lib/store/common.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~addcontext",
    "function/index.html#static-function-addContext",
    "<span>addContext</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/sagas/index.js~addcontext",
    "function/index.html#static-function-addContext",
    "<span>addContext</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~addinstance",
    "function/index.html#static-function-addInstance",
    "<span>addInstance</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/sagas/index.js~addinstance",
    "function/index.html#static-function-addInstance",
    "<span>addInstance</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/solidity/actions/index.js~addsource",
    "function/index.html#static-function-addSource",
    "<span>addSource</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/solidity/sagas/index.js~addsource",
    "function/index.html#static-function-addSource",
    "<span>addSource</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/solidity/actions/index.js~addsourcemap",
    "function/index.html#static-function-addSourceMap",
    "<span>addSourceMap</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/solidity/sagas/index.js~addsourcemap",
    "function/index.html#static-function-addSourceMap",
    "<span>addSourceMap</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~advance",
    "function/index.html#static-function-advance",
    "<span>advance</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/sagas/index.js~advance",
    "function/index.html#static-function-advance",
    "<span>advance</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~allocatedeclarations",
    "function/index.html#static-function-allocateDeclarations",
    "<span>allocateDeclarations</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/actions/index.js~assign",
    "function/index.html#static-function-assign",
    "<span>assign</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/ast/selectors/index.js~ast",
    "variable/index.html#static-variable-ast",
    "<span>ast</span> <span class=\"search-result-import-path\">truffle-debugger/lib/ast/selectors/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~basedefinition",
    "function/index.html#static-function-baseDefinition",
    "<span>baseDefinition</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/sagas/index.js~begin",
    "function/index.html#static-function-begin",
    "<span>begin</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~beginstep",
    "function/index.html#static-function-beginStep",
    "<span>beginStep</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~call",
    "function/index.html#static-function-call",
    "<span>call</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/reducers.js~callstack",
    "function/index.html#static-function-callstack",
    "<span>callstack</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/reducers.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/sagas/index.js~callstacksaga",
    "function/index.html#static-function-callstackSaga",
    "<span>callstackSaga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/memory.js~chunk",
    "function/index.html#static-function-chunk",
    "<span>chunk</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/memory.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~cleanbignumbers",
    "function/index.html#static-function-cleanBigNumbers",
    "<span>cleanBigNumbers</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/store/common.js~configurestore",
    "function/index.html#static-function-configureStore",
    "<span>configureStore</span> <span class=\"search-result-import-path\">truffle-debugger/lib/store/common.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/store/development.js~configurestore",
    "function/index.html#static-function-configureStore",
    "<span>configureStore</span> <span class=\"search-result-import-path\">truffle-debugger/lib/store/development.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~continueuntil",
    "function/index.html#static-function-continueUntil",
    "<span>continueUntil</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/selectors/index.js~controller",
    "variable/index.html#static-variable-controller",
    "<span>controller</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/selectors/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/selectors/index.js~data",
    "variable/index.html#static-variable-data",
    "<span>data</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/selectors/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/data/actions/index.js~declare",
    "function/index.html#static-function-declare",
    "<span>declare</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/sagas/index.js~declare",
    "function/index.html#static-function-declare",
    "<span>declare</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/index.js~decode",
    "function/index.html#static-function-decode",
    "<span>decode</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/index.js~decodememoryreference",
    "function/index.html#static-function-decodeMemoryReference",
    "<span>decodeMemoryReference</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/index.js~decodestoragereference",
    "function/index.html#static-function-decodeStorageReference",
    "<span>decodeStorageReference</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/index.js~decodevalue",
    "function/index.html#static-function-decodeValue",
    "<span>decodeValue</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/ast/actions/index.js~donevisiting",
    "function/index.html#static-function-doneVisiting",
    "<span>doneVisiting</span> <span class=\"search-result-import-path\">truffle-debugger/lib/ast/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~endtrace",
    "function/index.html#static-function-endTrace",
    "<span>endTrace</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/session/actions/index.js~error",
    "function/index.html#static-function-error",
    "<span>error</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~error",
    "function/index.html#static-function-error",
    "<span>error</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/selectors/index.js~evm",
    "variable/index.html#static-variable-evm",
    "<span>evm</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/selectors/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~fetchbinary",
    "function/index.html#static-function-fetchBinary",
    "<span>fetchBinary</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/session/actions/index.js~finish",
    "function/index.html#static-function-finish",
    "<span>finish</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/solidity/reducers.js~functiondepth",
    "function/index.html#static-function-functionDepth",
    "<span>functionDepth</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/reducers.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/reducers.js~index",
    "function/index.html#static-function-index",
    "<span>index</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/reducers.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~init",
    "function/index.html#static-function-init",
    "<span>init</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~inspect",
    "function/index.html#static-function-inspect",
    "<span>inspect</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/web3/sagas/index.js~inspecttransaction",
    "function/index.html#static-function-inspectTransaction",
    "<span>inspectTransaction</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~interrupt",
    "function/index.html#static-function-interrupt",
    "<span>interrupt</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~isreference",
    "function/index.html#static-function-isReference",
    "<span>isReference</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/solidity/actions/index.js~jump",
    "function/index.html#static-function-jump",
    "<span>jump</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~keccak256",
    "function/index.html#static-function-keccak256",
    "<span>keccak256</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/helpers/index.js~keccak256",
    "function/index.html#static-function-keccak256",
    "<span>keccak256</span> <span class=\"search-result-import-path\">truffle-debugger/lib/helpers/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~next",
    "function/index.html#static-function-next",
    "<span>next</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/web3/sagas/index.js~obtainbinaries",
    "function/index.html#static-function-obtainBinaries",
    "<span>obtainBinaries</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/helpers/index.js~prefixname",
    "function/index.html#static-function-prefixName",
    "<span>prefixName</span> <span class=\"search-result-import-path\">truffle-debugger/lib/helpers/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/sagas/index.js~processtrace",
    "function/index.html#static-function-processTrace",
    "<span>processTrace</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/index.js~read",
    "function/index.html#static-function-read",
    "<span>read</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/memory.js~read",
    "function/index.html#static-function-read",
    "<span>read</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/memory.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/storage.js~read",
    "function/index.html#static-function-read",
    "<span>read</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/storage.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/memory.js~readbytes",
    "function/index.html#static-function-readBytes",
    "<span>readBytes</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/memory.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/storage.js~readrange",
    "function/index.html#static-function-readRange",
    "<span>readRange</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/storage.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/session/actions/index.js~ready",
    "function/index.html#static-function-ready",
    "<span>ready</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~receiveaddresses",
    "function/index.html#static-function-receiveAddresses",
    "<span>receiveAddresses</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~receivebinary",
    "function/index.html#static-function-receiveBinary",
    "<span>receiveBinary</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~receivecall",
    "function/index.html#static-function-receiveCall",
    "<span>receiveCall</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/web3/actions/index.js~receivetrace",
    "function/index.html#static-function-receiveTrace",
    "<span>receiveTrace</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/session/actions/index.js~recordcontracts",
    "function/index.html#static-function-recordContracts",
    "<span>recordContracts</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/session/reducers.js~reducestate",
    "variable/index.html#static-variable-reduceState",
    "<span>reduceState</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/data/reducers.js~reducer",
    "variable/index.html#static-variable-reducer",
    "<span>reducer</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/evm/reducers.js~reducer",
    "variable/index.html#static-variable-reducer",
    "<span>reducer</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/solidity/reducers.js~reducer",
    "variable/index.html#static-variable-reducer",
    "<span>reducer</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/trace/reducers.js~reducer",
    "variable/index.html#static-variable-reducer",
    "<span>reducer</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/reducers.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~referencetype",
    "function/index.html#static-function-referenceType",
    "<span>referenceType</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/actions/index.js~returncall",
    "function/index.html#static-function-returnCall",
    "<span>returnCall</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/ast/sagas/index.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/ast/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/sagas/index.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/sagas/index.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/evm/sagas/index.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/evm/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/session/sagas/index.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/solidity/sagas/index.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/sagas/index.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/web3/sagas/index.js~saga",
    "function/index.html#static-function-saga",
    "<span>saga</span> <span class=\"search-result-import-path\">truffle-debugger/lib/web3/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~savesteps",
    "function/index.html#static-function-saveSteps",
    "<span>saveSteps</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/actions/index.js~scope",
    "function/index.html#static-function-scope",
    "<span>scope</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/sagas/index.js~scope",
    "function/index.html#static-function-scope",
    "<span>scope</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/session/reducers.js~session",
    "function/index.html#static-function-session",
    "<span>session</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/reducers.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/session/selectors/index.js~session",
    "variable/index.html#static-variable-session",
    "<span>session</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/selectors/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/solidity/selectors/index.js~solidity",
    "variable/index.html#static-variable-solidity",
    "<span>solidity</span> <span class=\"search-result-import-path\">truffle-debugger/lib/solidity/selectors/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~specifiedsize",
    "function/index.html#static-function-specifiedSize",
    "<span>specifiedSize</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/session/actions/index.js~start",
    "function/index.html#static-function-start",
    "<span>start</span> <span class=\"search-result-import-path\">truffle-debugger/lib/session/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~stepinto",
    "function/index.html#static-function-stepInto",
    "<span>stepInto</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~stepnext",
    "function/index.html#static-function-stepNext",
    "<span>stepNext</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~stepout",
    "function/index.html#static-function-stepOut",
    "<span>stepOut</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/controller/actions/index.js~stepover",
    "function/index.html#static-function-stepOver",
    "<span>stepOver</span> <span class=\"search-result-import-path\">truffle-debugger/lib/controller/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/reducers.js~steps",
    "function/index.html#static-function-steps",
    "<span>steps</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/reducers.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~storagesize",
    "function/index.html#static-function-storageSize",
    "<span>storageSize</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~tick",
    "function/index.html#static-function-tick",
    "<span>tick</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~tobignumber",
    "function/index.html#static-function-toBigNumber",
    "<span>toBigNumber</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~tobytes",
    "function/index.html#static-function-toBytes",
    "<span>toBytes</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~tohexstring",
    "function/index.html#static-function-toHexString",
    "<span>toHexString</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~tosignedbignumber",
    "function/index.html#static-function-toSignedBigNumber",
    "<span>toSignedBigNumber</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/actions/index.js~tock",
    "function/index.html#static-function-tock",
    "<span>tock</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/selectors/index.js~trace",
    "variable/index.html#static-variable-trace",
    "<span>trace</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/selectors/index.js</span>",
    "variable"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~typeclass",
    "function/index.html#static-function-typeClass",
    "<span>typeClass</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/data/decode/utils.js~typeidentifier",
    "function/index.html#static-function-typeIdentifier",
    "<span>typeIdentifier</span> <span class=\"search-result-import-path\">truffle-debugger/lib/data/decode/utils.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/ast/actions/index.js~visit",
    "function/index.html#static-function-visit",
    "<span>visit</span> <span class=\"search-result-import-path\">truffle-debugger/lib/ast/actions/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/ast/sagas/index.js~visitall",
    "function/index.html#static-function-visitAll",
    "<span>visitAll</span> <span class=\"search-result-import-path\">truffle-debugger/lib/ast/sagas/index.js</span>",
    "function"
  ],
  [
    "truffle-debugger/lib/trace/sagas/index.js~wait",
    "function/index.html#static-function-wait",
    "<span>wait</span> <span class=\"search-result-import-path\">truffle-debugger/lib/trace/sagas/index.js</span>",
    "function"
  ],
  [
    "lib/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "lib/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "lib/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "lib/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "lib/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "lib/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "lib/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "lib/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "lib/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "lib/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "lib/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "lib/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "lib/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "lib/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "lib/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "lib/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "lib/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "lib/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "lib/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "lib/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "lib/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "lib/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "lib/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "lib/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "lib/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "lib/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~String",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "lib/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "lib/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "lib/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "lib/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "lib/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "lib/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "lib/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "lib/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "lib/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "lib/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "lib/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "lib/.external-ecmascript.js~function",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "lib/.external-ecmascript.js~null",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "lib/.external-ecmascript.js~number",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "lib/.external-ecmascript.js~object",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "lib/.external-ecmascript.js~string",
    "external"
  ],
  [
    "lib/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "lib/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "lib/ast/actions/index.js",
    "file/lib/ast/actions/index.js.html",
    "lib/ast/actions/index.js",
    "file"
  ],
  [
    "lib/ast/map.js",
    "file/lib/ast/map.js.html",
    "lib/ast/map.js",
    "file"
  ],
  [
    "lib/ast/sagas/index.js",
    "file/lib/ast/sagas/index.js.html",
    "lib/ast/sagas/index.js",
    "file"
  ],
  [
    "lib/ast/selectors/index.js",
    "file/lib/ast/selectors/index.js.html",
    "lib/ast/selectors/index.js",
    "file"
  ],
  [
    "lib/ast/selectors/index.js",
    "file/lib/ast/selectors/index.js.html",
    "lib/ast/selectors/index.js",
    "file"
  ],
  [
    "lib/ast/selectors/index.js~ast",
    "function/index.html#static-function-ast",
    "lib/ast/selectors/index.js~ast",
    "function"
  ],
  [
    "lib/ast/selectors/index.js~ast.ast.current",
    "function/index.html#static-function-ast.current",
    "lib/ast/selectors/index.js~ast.ast.current",
    "function"
  ],
  [
    "lib/ast/selectors/index.js~ast.ast.views",
    "function/index.html#static-function-ast.views",
    "lib/ast/selectors/index.js~ast.ast.views",
    "function"
  ],
  [
    "lib/ast/selectors/index.js~ast.current.ast.current.index",
    "function/index.html#static-function-ast.current.index",
    "lib/ast/selectors/index.js~ast.current.ast.current.index",
    "function"
  ],
  [
    "lib/ast/selectors/index.js~ast.current.ast.current.node",
    "function/index.html#static-function-ast.current.node",
    "lib/ast/selectors/index.js~ast.current.ast.current.node",
    "function"
  ],
  [
    "lib/ast/selectors/index.js~ast.current.ast.current.pointer",
    "function/index.html#static-function-ast.current.pointer",
    "lib/ast/selectors/index.js~ast.current.ast.current.pointer",
    "function"
  ],
  [
    "lib/ast/selectors/index.js~ast.current.ast.current.tree",
    "function/index.html#static-function-ast.current.tree",
    "lib/ast/selectors/index.js~ast.current.ast.current.tree",
    "function"
  ],
  [
    "lib/ast/selectors/index.js~ast.views.ast.views.sources",
    "function/index.html#static-function-ast.views.sources",
    "lib/ast/selectors/index.js~ast.views.ast.views.sources",
    "function"
  ],
  [
    "lib/controller/actions/index.js",
    "file/lib/controller/actions/index.js.html",
    "lib/controller/actions/index.js",
    "file"
  ],
  [
    "lib/controller/sagas/index.js",
    "file/lib/controller/sagas/index.js.html",
    "lib/controller/sagas/index.js",
    "file"
  ],
  [
    "lib/controller/selectors/index.js",
    "file/lib/controller/selectors/index.js.html",
    "lib/controller/selectors/index.js",
    "file"
  ],
  [
    "lib/controller/selectors/index.js",
    "file/lib/controller/selectors/index.js.html",
    "lib/controller/selectors/index.js",
    "file"
  ],
  [
    "lib/controller/selectors/index.js~controller",
    "function/index.html#static-function-controller",
    "lib/controller/selectors/index.js~controller",
    "function"
  ],
  [
    "lib/controller/selectors/index.js~controller.controller.current",
    "function/index.html#static-function-controller.current",
    "lib/controller/selectors/index.js~controller.controller.current",
    "function"
  ],
  [
    "lib/controller/selectors/index.js~controller.current.controller.current.executioncontext",
    "function/index.html#static-function-controller.current.executionContext",
    "lib/controller/selectors/index.js~controller.current.controller.current.executionContext",
    "function"
  ],
  [
    "lib/controller/selectors/index.js~controller.current.controller.current.functiondepth",
    "function/index.html#static-function-controller.current.functionDepth",
    "lib/controller/selectors/index.js~controller.current.controller.current.functionDepth",
    "function"
  ],
  [
    "lib/controller/selectors/index.js~controller.current.controller.current.location",
    "function/index.html#static-function-controller.current.location",
    "lib/controller/selectors/index.js~controller.current.controller.current.location",
    "function"
  ],
  [
    "lib/controller/selectors/index.js~controller.current.controller.current.willjump",
    "function/index.html#static-function-controller.current.willJump",
    "lib/controller/selectors/index.js~controller.current.controller.current.willJump",
    "function"
  ],
  [
    "lib/controller/selectors/index.js~controller.current.location.controller.current.location.ismultiline",
    "function/index.html#static-function-controller.current.location.isMultiline",
    "lib/controller/selectors/index.js~controller.current.location.controller.current.location.isMultiline",
    "function"
  ],
  [
    "lib/controller/selectors/index.js~controller.current.location.controller.current.location.node",
    "function/index.html#static-function-controller.current.location.node",
    "lib/controller/selectors/index.js~controller.current.location.controller.current.location.node",
    "function"
  ],
  [
    "lib/controller/selectors/index.js~controller.current.location.controller.current.location.sourcerange",
    "function/index.html#static-function-controller.current.location.sourceRange",
    "lib/controller/selectors/index.js~controller.current.location.controller.current.location.sourceRange",
    "function"
  ],
  [
    "lib/data/actions/index.js",
    "file/lib/data/actions/index.js.html",
    "lib/data/actions/index.js",
    "file"
  ],
  [
    "lib/data/decode/index.js",
    "file/lib/data/decode/index.js.html",
    "lib/data/decode/index.js",
    "file"
  ],
  [
    "lib/data/decode/memory.js",
    "file/lib/data/decode/memory.js.html",
    "lib/data/decode/memory.js",
    "file"
  ],
  [
    "lib/data/decode/storage.js",
    "file/lib/data/decode/storage.js.html",
    "lib/data/decode/storage.js",
    "file"
  ],
  [
    "lib/data/decode/utils.js",
    "file/lib/data/decode/utils.js.html",
    "lib/data/decode/utils.js",
    "file"
  ],
  [
    "lib/data/reducers.js",
    "file/lib/data/reducers.js.html",
    "lib/data/reducers.js",
    "file"
  ],
  [
    "lib/data/sagas/index.js",
    "file/lib/data/sagas/index.js.html",
    "lib/data/sagas/index.js",
    "file"
  ],
  [
    "lib/data/selectors/index.js",
    "file/lib/data/selectors/index.js.html",
    "lib/data/selectors/index.js",
    "file"
  ],
  [
    "lib/data/selectors/index.js",
    "file/lib/data/selectors/index.js.html",
    "lib/data/selectors/index.js",
    "file"
  ],
  [
    "lib/data/selectors/index.js~current",
    "function/index.html#static-function-current",
    "lib/data/selectors/index.js~current",
    "function"
  ],
  [
    "lib/data/selectors/index.js~current.current.identifiers",
    "function/index.html#static-function-current.identifiers",
    "lib/data/selectors/index.js~current.current.identifiers",
    "function"
  ],
  [
    "lib/data/selectors/index.js~current.current.scope",
    "function/index.html#static-function-current.scope",
    "lib/data/selectors/index.js~current.current.scope",
    "function"
  ],
  [
    "lib/data/selectors/index.js~current.identifiers.current.identifiers._",
    "function/index.html#static-function-current.identifiers._",
    "lib/data/selectors/index.js~current.identifiers.current.identifiers._",
    "function"
  ],
  [
    "lib/data/selectors/index.js~current.identifiers.current.identifiers.definitions",
    "function/index.html#static-function-current.identifiers.definitions",
    "lib/data/selectors/index.js~current.identifiers.current.identifiers.definitions",
    "function"
  ],
  [
    "lib/data/selectors/index.js~current.identifiers.current.identifiers.refs",
    "function/index.html#static-function-current.identifiers.refs",
    "lib/data/selectors/index.js~current.identifiers.current.identifiers.refs",
    "function"
  ],
  [
    "lib/data/selectors/index.js~current.scope.current.scope.id",
    "function/index.html#static-function-current.scope.id",
    "lib/data/selectors/index.js~current.scope.current.scope.id",
    "function"
  ],
  [
    "lib/data/selectors/index.js~info",
    "function/index.html#static-function-info",
    "lib/data/selectors/index.js~info",
    "function"
  ],
  [
    "lib/data/selectors/index.js~info.info.scopes",
    "function/index.html#static-function-info.scopes",
    "lib/data/selectors/index.js~info.info.scopes",
    "function"
  ],
  [
    "lib/data/selectors/index.js~memory",
    "function/index.html#static-function-memory",
    "lib/data/selectors/index.js~memory",
    "function"
  ],
  [
    "lib/data/selectors/index.js~next",
    "function/index.html#static-function-next",
    "lib/data/selectors/index.js~next",
    "function"
  ],
  [
    "lib/data/selectors/index.js~proc",
    "function/index.html#static-function-proc",
    "lib/data/selectors/index.js~proc",
    "function"
  ],
  [
    "lib/data/selectors/index.js~proc.proc.assignments",
    "function/index.html#static-function-proc.assignments",
    "lib/data/selectors/index.js~proc.proc.assignments",
    "function"
  ],
  [
    "lib/data/selectors/index.js~stack",
    "function/index.html#static-function-stack",
    "lib/data/selectors/index.js~stack",
    "function"
  ],
  [
    "lib/data/selectors/index.js~storage",
    "function/index.html#static-function-storage",
    "lib/data/selectors/index.js~storage",
    "function"
  ],
  [
    "lib/data/selectors/index.js~views",
    "function/index.html#static-function-views",
    "lib/data/selectors/index.js~views",
    "function"
  ],
  [
    "lib/data/selectors/index.js~views.scopes.views.scopes.inlined",
    "function/index.html#static-function-views.scopes.inlined",
    "lib/data/selectors/index.js~views.scopes.views.scopes.inlined",
    "function"
  ],
  [
    "lib/data/selectors/index.js~views.views.decoder",
    "function/index.html#static-function-views.decoder",
    "lib/data/selectors/index.js~views.views.decoder",
    "function"
  ],
  [
    "lib/data/selectors/index.js~views.views.scopes",
    "function/index.html#static-function-views.scopes",
    "lib/data/selectors/index.js~views.views.scopes",
    "function"
  ],
  [
    "lib/debugger.js",
    "file/lib/debugger.js.html",
    "lib/debugger.js",
    "file"
  ],
  [
    "lib/debugger.js~contract",
    "typedef/index.html#static-typedef-Contract",
    "lib/debugger.js~Contract",
    "typedef"
  ],
  [
    "lib/debugger.js~debugger#connect",
    "class/lib/debugger.js~Debugger.html#instance-method-connect",
    "lib/debugger.js~Debugger#connect",
    "method"
  ],
  [
    "lib/debugger.js~debugger.fortx",
    "class/lib/debugger.js~Debugger.html#static-method-forTx",
    "lib/debugger.js~Debugger.forTx",
    "method"
  ],
  [
    "lib/debugger.js~debugger.selectors",
    "class/lib/debugger.js~Debugger.html#static-get-selectors",
    "lib/debugger.js~Debugger.selectors",
    "member"
  ],
  [
    "lib/evm/actions/index.js",
    "file/lib/evm/actions/index.js.html",
    "lib/evm/actions/index.js",
    "file"
  ],
  [
    "lib/evm/reducers.js",
    "file/lib/evm/reducers.js.html",
    "lib/evm/reducers.js",
    "file"
  ],
  [
    "lib/evm/sagas/index.js",
    "file/lib/evm/sagas/index.js.html",
    "lib/evm/sagas/index.js",
    "file"
  ],
  [
    "lib/evm/selectors/index.js",
    "file/lib/evm/selectors/index.js.html",
    "lib/evm/selectors/index.js",
    "file"
  ],
  [
    "lib/evm/selectors/index.js",
    "file/lib/evm/selectors/index.js.html",
    "lib/evm/selectors/index.js",
    "file"
  ],
  [
    "lib/evm/selectors/index.js~calladdress",
    "function/index.html#static-function-callAddress",
    "lib/evm/selectors/index.js~callAddress",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~createbinary",
    "function/index.html#static-function-createBinary",
    "lib/evm/selectors/index.js~createBinary",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~current",
    "function/index.html#static-function-current",
    "lib/evm/selectors/index.js~current",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~current.current.call",
    "function/index.html#static-function-current.call",
    "lib/evm/selectors/index.js~current.current.call",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~current.current.callstack",
    "function/index.html#static-function-current.callstack",
    "lib/evm/selectors/index.js~current.current.callstack",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~current.current.context",
    "function/index.html#static-function-current.context",
    "lib/evm/selectors/index.js~current.current.context",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~info",
    "function/index.html#static-function-info",
    "lib/evm/selectors/index.js~info",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~info.binaries.info.binaries.search",
    "function/index.html#static-function-info.binaries.search",
    "lib/evm/selectors/index.js~info.binaries.info.binaries.search",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~info.binaries.search.info.binaries.search.toregexp",
    "function/index.html#static-function-info.binaries.search.toRegExp",
    "lib/evm/selectors/index.js~info.binaries.search.info.binaries.search.toRegExp",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~info.info.binaries",
    "function/index.html#static-function-info.binaries",
    "lib/evm/selectors/index.js~info.info.binaries",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~info.info.contexts",
    "function/index.html#static-function-info.contexts",
    "lib/evm/selectors/index.js~info.info.contexts",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~info.info.instances",
    "function/index.html#static-function-info.instances",
    "lib/evm/selectors/index.js~info.info.instances",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~iscall",
    "function/index.html#static-function-isCall",
    "lib/evm/selectors/index.js~isCall",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~iscreate",
    "function/index.html#static-function-isCreate",
    "lib/evm/selectors/index.js~isCreate",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~ishalting",
    "function/index.html#static-function-isHalting",
    "lib/evm/selectors/index.js~isHalting",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~isjump",
    "function/index.html#static-function-isJump",
    "lib/evm/selectors/index.js~isJump",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~next",
    "function/index.html#static-function-next",
    "lib/evm/selectors/index.js~next",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~programcounter",
    "function/index.html#static-function-programCounter",
    "lib/evm/selectors/index.js~programCounter",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~state",
    "function/index.html#static-function-state",
    "lib/evm/selectors/index.js~state",
    "function"
  ],
  [
    "lib/evm/selectors/index.js~trace",
    "function/index.html#static-function-trace",
    "lib/evm/selectors/index.js~trace",
    "function"
  ],
  [
    "lib/helpers/index.js",
    "file/lib/helpers/index.js.html",
    "lib/helpers/index.js",
    "file"
  ],
  [
    "lib/session/actions/index.js",
    "file/lib/session/actions/index.js.html",
    "lib/session/actions/index.js",
    "file"
  ],
  [
    "lib/session/index.js",
    "file/lib/session/index.js.html",
    "lib/session/index.js",
    "file"
  ],
  [
    "lib/session/index.js~session#advance",
    "class/lib/session/index.js~Session.html#instance-method-advance",
    "lib/session/index.js~Session#advance",
    "method"
  ],
  [
    "lib/session/index.js~session#continueuntil",
    "class/lib/session/index.js~Session.html#instance-method-continueUntil",
    "lib/session/index.js~Session#continueUntil",
    "method"
  ],
  [
    "lib/session/index.js~session#dispatch",
    "class/lib/session/index.js~Session.html#instance-method-dispatch",
    "lib/session/index.js~Session#dispatch",
    "method"
  ],
  [
    "lib/session/index.js~session#failed",
    "class/lib/session/index.js~Session.html#instance-get-failed",
    "lib/session/index.js~Session#failed",
    "member"
  ],
  [
    "lib/session/index.js~session#finished",
    "class/lib/session/index.js~Session.html#instance-get-finished",
    "lib/session/index.js~Session#finished",
    "member"
  ],
  [
    "lib/session/index.js~session#interrupt",
    "class/lib/session/index.js~Session.html#instance-method-interrupt",
    "lib/session/index.js~Session#interrupt",
    "method"
  ],
  [
    "lib/session/index.js~session#ready",
    "class/lib/session/index.js~Session.html#instance-method-ready",
    "lib/session/index.js~Session#ready",
    "method"
  ],
  [
    "lib/session/index.js~session#state",
    "class/lib/session/index.js~Session.html#instance-get-state",
    "lib/session/index.js~Session#state",
    "member"
  ],
  [
    "lib/session/index.js~session#stepinto",
    "class/lib/session/index.js~Session.html#instance-method-stepInto",
    "lib/session/index.js~Session#stepInto",
    "method"
  ],
  [
    "lib/session/index.js~session#stepnext",
    "class/lib/session/index.js~Session.html#instance-method-stepNext",
    "lib/session/index.js~Session#stepNext",
    "method"
  ],
  [
    "lib/session/index.js~session#stepout",
    "class/lib/session/index.js~Session.html#instance-method-stepOut",
    "lib/session/index.js~Session#stepOut",
    "method"
  ],
  [
    "lib/session/index.js~session#stepover",
    "class/lib/session/index.js~Session.html#instance-method-stepOver",
    "lib/session/index.js~Session#stepOver",
    "method"
  ],
  [
    "lib/session/index.js~session#view",
    "class/lib/session/index.js~Session.html#instance-method-view",
    "lib/session/index.js~Session#view",
    "method"
  ],
  [
    "lib/session/reducers.js",
    "file/lib/session/reducers.js.html",
    "lib/session/reducers.js",
    "file"
  ],
  [
    "lib/session/sagas/index.js",
    "file/lib/session/sagas/index.js.html",
    "lib/session/sagas/index.js",
    "file"
  ],
  [
    "lib/session/selectors/index.js",
    "file/lib/session/selectors/index.js.html",
    "lib/session/selectors/index.js",
    "file"
  ],
  [
    "lib/session/selectors/index.js",
    "file/lib/session/selectors/index.js.html",
    "lib/session/selectors/index.js",
    "file"
  ],
  [
    "lib/session/selectors/index.js~info",
    "function/index.html#static-function-info",
    "lib/session/selectors/index.js~info",
    "function"
  ],
  [
    "lib/session/selectors/index.js~info.info.affectedinstances",
    "function/index.html#static-function-info.affectedInstances",
    "lib/session/selectors/index.js~info.info.affectedInstances",
    "function"
  ],
  [
    "lib/solidity/actions/index.js",
    "file/lib/solidity/actions/index.js.html",
    "lib/solidity/actions/index.js",
    "file"
  ],
  [
    "lib/solidity/reducers.js",
    "file/lib/solidity/reducers.js.html",
    "lib/solidity/reducers.js",
    "file"
  ],
  [
    "lib/solidity/sagas/index.js",
    "file/lib/solidity/sagas/index.js.html",
    "lib/solidity/sagas/index.js",
    "file"
  ],
  [
    "lib/solidity/selectors/index.js",
    "file/lib/solidity/selectors/index.js.html",
    "lib/solidity/selectors/index.js",
    "file"
  ],
  [
    "lib/solidity/selectors/index.js",
    "file/lib/solidity/selectors/index.js.html",
    "lib/solidity/selectors/index.js",
    "file"
  ],
  [
    "lib/solidity/selectors/index.js~current",
    "function/index.html#static-function-current",
    "lib/solidity/selectors/index.js~current",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~current.current.functiondepth",
    "function/index.html#static-function-current.functionDepth",
    "lib/solidity/selectors/index.js~current.current.functionDepth",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~current.current.instruction",
    "function/index.html#static-function-current.instruction",
    "lib/solidity/selectors/index.js~current.current.instruction",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~current.current.instructionatprogramcounter",
    "function/index.html#static-function-current.instructionAtProgramCounter",
    "lib/solidity/selectors/index.js~current.current.instructionAtProgramCounter",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~current.current.instructions",
    "function/index.html#static-function-current.instructions",
    "lib/solidity/selectors/index.js~current.current.instructions",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~current.current.ismultiline",
    "function/index.html#static-function-current.isMultiline",
    "lib/solidity/selectors/index.js~current.current.isMultiline",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~current.current.issourcerangefinal",
    "function/index.html#static-function-current.isSourceRangeFinal",
    "lib/solidity/selectors/index.js~current.current.isSourceRangeFinal",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~current.current.jumpdirection",
    "function/index.html#static-function-current.jumpDirection",
    "lib/solidity/selectors/index.js~current.current.jumpDirection",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~current.current.source",
    "function/index.html#static-function-current.source",
    "lib/solidity/selectors/index.js~current.current.source",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~current.current.sourcemap",
    "function/index.html#static-function-current.sourceMap",
    "lib/solidity/selectors/index.js~current.current.sourceMap",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~current.current.sourcerange",
    "function/index.html#static-function-current.sourceRange",
    "lib/solidity/selectors/index.js~current.current.sourceRange",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~current.current.willjump",
    "function/index.html#static-function-current.willJump",
    "lib/solidity/selectors/index.js~current.current.willJump",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~info",
    "function/index.html#static-function-info",
    "lib/solidity/selectors/index.js~info",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~info.info.sourcemaps",
    "function/index.html#static-function-info.sourceMaps",
    "lib/solidity/selectors/index.js~info.info.sourceMaps",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~info.info.sources",
    "function/index.html#static-function-info.sources",
    "lib/solidity/selectors/index.js~info.info.sources",
    "function"
  ],
  [
    "lib/solidity/selectors/index.js~state",
    "function/index.html#static-function-state",
    "lib/solidity/selectors/index.js~state",
    "function"
  ],
  [
    "lib/store/common.js",
    "file/lib/store/common.js.html",
    "lib/store/common.js",
    "file"
  ],
  [
    "lib/store/development.js",
    "file/lib/store/development.js.html",
    "lib/store/development.js",
    "file"
  ],
  [
    "lib/store/index.js",
    "file/lib/store/index.js.html",
    "lib/store/index.js",
    "file"
  ],
  [
    "lib/store/production.js",
    "file/lib/store/production.js.html",
    "lib/store/production.js",
    "file"
  ],
  [
    "lib/store/test.js",
    "file/lib/store/test.js.html",
    "lib/store/test.js",
    "file"
  ],
  [
    "lib/trace/actions/index.js",
    "file/lib/trace/actions/index.js.html",
    "lib/trace/actions/index.js",
    "file"
  ],
  [
    "lib/trace/reducers.js",
    "file/lib/trace/reducers.js.html",
    "lib/trace/reducers.js",
    "file"
  ],
  [
    "lib/trace/sagas/index.js",
    "file/lib/trace/sagas/index.js.html",
    "lib/trace/sagas/index.js",
    "file"
  ],
  [
    "lib/trace/selectors/index.js",
    "file/lib/trace/selectors/index.js.html",
    "lib/trace/selectors/index.js",
    "file"
  ],
  [
    "lib/trace/selectors/index.js",
    "file/lib/trace/selectors/index.js.html",
    "lib/trace/selectors/index.js",
    "file"
  ],
  [
    "lib/trace/selectors/index.js~index",
    "function/index.html#static-function-index",
    "lib/trace/selectors/index.js~index",
    "function"
  ],
  [
    "lib/trace/selectors/index.js~next",
    "function/index.html#static-function-next",
    "lib/trace/selectors/index.js~next",
    "function"
  ],
  [
    "lib/trace/selectors/index.js~step",
    "function/index.html#static-function-step",
    "lib/trace/selectors/index.js~step",
    "function"
  ],
  [
    "lib/trace/selectors/index.js~steps",
    "function/index.html#static-function-steps",
    "lib/trace/selectors/index.js~steps",
    "function"
  ],
  [
    "lib/trace/selectors/index.js~stepsremaining",
    "function/index.html#static-function-stepsRemaining",
    "lib/trace/selectors/index.js~stepsRemaining",
    "function"
  ],
  [
    "lib/web3/actions/index.js",
    "file/lib/web3/actions/index.js.html",
    "lib/web3/actions/index.js",
    "file"
  ],
  [
    "lib/web3/adapter.js",
    "file/lib/web3/adapter.js.html",
    "lib/web3/adapter.js",
    "file"
  ],
  [
    "lib/web3/adapter.js~web3adapter#constructor",
    "class/lib/web3/adapter.js~Web3Adapter.html#instance-constructor-constructor",
    "lib/web3/adapter.js~Web3Adapter#constructor",
    "method"
  ],
  [
    "lib/web3/adapter.js~web3adapter#getdeployedcode",
    "class/lib/web3/adapter.js~Web3Adapter.html#instance-method-getDeployedCode",
    "lib/web3/adapter.js~Web3Adapter#getDeployedCode",
    "method"
  ],
  [
    "lib/web3/adapter.js~web3adapter#getreceipt",
    "class/lib/web3/adapter.js~Web3Adapter.html#instance-method-getReceipt",
    "lib/web3/adapter.js~Web3Adapter#getReceipt",
    "method"
  ],
  [
    "lib/web3/adapter.js~web3adapter#gettrace",
    "class/lib/web3/adapter.js~Web3Adapter.html#instance-method-getTrace",
    "lib/web3/adapter.js~Web3Adapter#getTrace",
    "method"
  ],
  [
    "lib/web3/adapter.js~web3adapter#gettransaction",
    "class/lib/web3/adapter.js~Web3Adapter.html#instance-method-getTransaction",
    "lib/web3/adapter.js~Web3Adapter#getTransaction",
    "method"
  ],
  [
    "lib/web3/adapter.js~web3adapter#web3",
    "class/lib/web3/adapter.js~Web3Adapter.html#instance-member-web3",
    "lib/web3/adapter.js~Web3Adapter#web3",
    "member"
  ],
  [
    "lib/web3/sagas/index.js",
    "file/lib/web3/sagas/index.js.html",
    "lib/web3/sagas/index.js",
    "file"
  ]
]